### ISSUE TITLE
Question about Eq. 6 in the paper and the implementation

### ISSUE THREAD

**Issue by Terminator8758** [Wangt-CN/EqInv#1]
Hi, thank you for sharing the implementation of your paper. The method provides a new and interesting perspective of learning from insufficient data. I have one question about Eq. (6) in paper and the implementation:

In Eq. (6) in your paper, the class-wise IRM loss is composed of per-environment supervised contrastive loss and the penalty term. However in vipriors_eqinv.py, the final loss seems to compute an overall in-batch supervised contrastive loss (loss_cont), and the per-environment supervised contrastive loss is not taken into account in loss_inv. May I know the reason for this? Thanks a lot.

**Comment by Wangt-CN** [comment]
Hi, thanks for your interests in our work and this is a very good comment.
Actually, the code now is a newer version. The behind reason is 2-fold:
1) The performances are similar. The possible reason is that the per-environment sc is mainly used to compute the invariant loss by rex which has been achieved. The global sc can play a similar role in the empirical risk part.
2) Using global sc can greatly simplify the code. Though we have computed the environment sc now, the gradient of it cannot backward to the backbone. Therefore, we choose to additionally use global sc to achieve this easily.
We will add some comments in our next version of the paper to clarify the confusion. Thanks again for your great comment.

**Comment by Terminator8758** [comment]
Thank you for the explanation.
